version: '3.8'

services:
  backend:
    build: ./backend/Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend/docker.env:/backend/.env
    ports:
      - 3001:3001
    networks:
      - visioconf
    depends_on:
      - database

  react-front:
    build: ./frontend/Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend/docker.env:/frontend/.env
    ports:
      - 3000:3000
    networks:
      - visioconf
    depends_on:
      - backend

  database:
    image: mongo:latest
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: visioconf
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/mongodb-data
    networks:
      - visioconf

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - database
    networks:
      - visioconf

networks:
  visioconf: